### ISSUE TITLE
Error when using `<Link>`: ReferenceError: process is not defined

### ISSUE THREAD

**Issue by bbigras** [wmalarski/qwik-next-auth-example#3] opened 2022-12-19 19:08 UTC
![image](https://user-images.githubusercontent.com/24027/208500909-18af0f41-4d14-4a0d-b86e-8432337679c2.png)

and I got this in the console:

```
rctx is undefined handleError@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:2430:28
runWatch/<@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:5226:20
promise callback*safeCall@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:333:28
runWatch@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:5221:12
runSubscriber@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:5068:16
executeWatchesBefore/<@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4778:24
executeWatchesBefore@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4777:39
async*renderMarked@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4655:15
scheduleFrame/containerState.$renderPromise$<@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4633:83
createPlatform/nextTick/</<@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:220:29
setTimeout handler*createPlatform/nextTick/<@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:219:27
nextTick@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:218:20
scheduleFrame@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4633:56
notifyWatch@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4628:22
notifyChange@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:4559:24
$notifySubs$@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:6120:25
set@http://localhost:5173/node_modules/@builder.io/qwik/core.mjs?v=099df598:1094:28
Link_component_a_onClick_kzjavhDI3L0@http://localhost:5173/src/link_component_a_onclick_kzjavhdi3l0.js:4:25
dispatch@http://localhost:5173/:206:35
async*processDocumentEvent@http://localhost:5173/:233:23
EventListener.handleEvent*addEventListener@http://localhost:5173/:261:79
push@http://localhost:5173/:267:37
push@http://localhost:5173/:277:37
@http://localhost:5173/:283:19
```

To reproduce you can try my "err-link" branch and click the "test" link, the error will happen after about a second.

https://github.com/bbigras/qwik-next-auth-example/tree/err-link

Here's the commit: https://github.com/bbigras/qwik-next-auth-example/commit/30c8052776d069b4eb5b8dcb36b459a95b13e58e

**Comment by bbigras** [comment] 2022-12-22 16:18
Any ideas?

**Comment by wmalarski** [comment] 2023-01-29 12:00
Hello. The issue is fixed now. Server-only code landed on the client-side.

Little note on what's happening and how to avoid this error:
1. During client-side navigation Qwik is fetching 'qwik-city-plan' file from server.
2. Together with this file Qwik fetches some client/server-side code for app pages and layouts.
3. Qwik decides which code is client/server and server-only during compilation. 
4. The compilation is also based on AST analysis.  
5. To help the compiler correctly detect between those two types we need to keep our code syntax clear and simple.
6. `onGet`, `onPost`, `loader$`, and `action$` functions should always be arrow functions without any wrappers.
7. `onGet`, `onPost`, `loader$`, and `action$` functions should be assigned and defined next `const` declaration. 

My code failed here:
```ts
export const { onGet, onPost } = QwikAuth(authOptions);
```
I fixed this by switching to
```ts
export const onGet = (event: RequestEvent) => {
  return QwikAuth(event, authOptions);
};
export const onPost = (event: RequestEvent) => {
  return QwikAuth(event, authOptions);
};
```

**Closed as completed by wmalarski** 2023-01-29 12:00 UTC
